"""
Streamlit front-end for local development that consumes two backend endpoints:

1) POST /procesar-factura -> accepts JSON {"texto_factura": "..."}
2) POST /generar-pdf -> accepts full invoice JSON and returns PDF bytes

Run backend locally:
  uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000

Run Streamlit locally:
  streamlit run streamlit_app.py

For testing with a deployed Streamlit app, expose backend with ngrok:
  ngrok http 8000
  export BACKEND_URL="https://xxxxx.ngrok.io"

The UI below lets you send raw text to /procesar-factura, view/edit the returned
JSON, and then send it to /generar-pdf to download the generated PDF.
"""

import os
import requests
import streamlit as st
import json
from typing import Any, Dict


# Resolve backend URL: env -> st.secrets -> default localhost
def get_backend_url() -> str:
    url = os.environ.get("BACKEND_URL")
    if not url:
        try:
            url = st.secrets.get("backend_url")
        except Exception:
            url = None
    return url or "http://localhost:8000"


BACKEND_URL = get_backend_url()


st.set_page_config(page_title="Facturador - Local", layout="wide")
st.title("🧾 Facturador (Frontend local)")
st.caption(f"Backend: {BACKEND_URL}")


def call_procesar_factura(texto: str) -> Dict[str, Any]:
    url = f"{BACKEND_URL}/procesar-factura"
    resp = requests.post(url, json={"texto_factura": texto}, timeout=30)
    resp.raise_for_status()
    return resp.json()


def call_generar_pdf(invoice_payload: Dict[str, Any]) -> bytes:
    url = f"{BACKEND_URL}/generar-pdf"
    resp = requests.post(url, json=invoice_payload, timeout=60)
    resp.raise_for_status()
    # If backend returns JSON (error), raise
    content_type = resp.headers.get("Content-Type", "")
    if "application/json" in content_type:
        data = resp.json()
        raise RuntimeError(f"Backend error: {data}")
    return resp.content


col1, col2 = st.columns([2, 3])

with col1:
    st.header("1) Extract invoice from text")
    texto = st.text_area("Paste invoice / receipt text here", height=200)
    if st.button("Process invoice (POST /procesar-factura)"):
        if not texto.strip():
            st.warning("Please enter invoice text first.")
        else:
            try:
                with st.spinner("Calling backend /procesar-factura..."):
                    result = call_procesar_factura(texto)
                    st.success("Received JSON from backend")
                    st.json(result)
                    st.session_state["invoice_data"] = result
            except Exception as e:
                st.error(f"Error calling backend: {e}")

    st.markdown("---")
    st.header("Or: Use manual/sample invoice JSON")
    sample = {
        "document_type": "Factura",
        "serie_correlativo": "F001-0000001",
        "emisor_nombre": "D&B COMBUSTIBLES DEL PERU S.A.C.",
        "emisor_ruc": "20521579782",
        "emisor_direccion": "CALLE LOS PRECIADOS N 156 INT 304, LIMA",
        "client": "Juan Perez",
        "client_address": "Dirección Desconocida - Lima",
        "ruc_simulado": "00000000000",
        "fecha_emision": "30/12/2024",
        "fecha_vencimiento": "30/12/2024",
        "forma_pago": "Contado",
        "moneda": "SOLES",
        "items": [
            {"descripcion": "Martillo", "cantidad": 1.0, "unidad_medida": "UNI", "precio_unitario": 20.0}
        ],
        "monto_letras": "VEINTE CON 00/100 SOLES"
    }

    if "invoice_data" not in st.session_state:
        st.session_state["invoice_data"] = sample

    invoice_text = st.text_area("Invoice JSON (editable)", value=json.dumps(st.session_state["invoice_data"], ensure_ascii=False, indent=2), height=300)
    if st.button("Update JSON preview"):
        try:
            parsed = json.loads(invoice_text)
            st.session_state["invoice_data"] = parsed
            st.success("Invoice JSON updated")
        except Exception as e:
            st.error(f"Invalid JSON: {e}")

with col2:
    st.header("2) Generate PDF from JSON")
    st.markdown("Use the JSON from the left column (editable) or the backend response.")
    if "invoice_data" in st.session_state:
        st.subheader("Current invoice preview")
        st.json(st.session_state["invoice_data"])

    if st.button("Generate PDF (POST /generar-pdf)"):
        try:
            payload = st.session_state.get("invoice_data")
            if not payload:
                st.warning("No invoice JSON available.")
            else:
                with st.spinner("Calling backend /generar-pdf..."):
                    pdf_bytes = call_generar_pdf(payload)
                    st.success("PDF generated by backend")
                    st.download_button("Download PDF", data=pdf_bytes, file_name="invoice.pdf", mime="application/pdf")
        except Exception as e:
            st.error(f"Error generating PDF: {e}")

    st.markdown("---")
    st.write("Advanced: set `BACKEND_URL` env var or `st.secrets['backend_url']` to point to a deployed backend.")
